#Data visualisation with base R and ggplot2 ####

#This script is intended to be a modular resource:
#Code is not provided as discrete blocks that you can copy wholesale;
#Instead, it's mostly individual lines that you can combine as you see fit

#We will split R commands into two categories:
#Those that determine how data is interpreted (the "back end")
#Those that determine how pretty it looks (the "front end")

#The back end (base R) ####
#Define example data
x <- runif(100)
y <- runif(100)
x_small <- runif(5)
y_small <- runif(5)
avg_binary <- function(x, y) (x + y) / 2
mat <- outer(x, y, avg_binary)
mat_small <- outer(x_small, y_small, avg_binary)
seq_x <- seq_y <- seq(0, 1, length.out = 10)
df <- data.frame("var1" = x, "var2" = y,
                 "group" = rep(1:5, each = 20),
                 "cgroup" = rep(letters[1:5], times = 20))
seq_df <- cbind(expand.grid("seq1" = seq_x, "seq2" = seq_y), "var1" = x)

#Main plots ####

#Basic scatterplot
plot(x, y, type = "p")
#Scatterplot connected by lines
plot(x, y, type = "l")

#Simple bar chart
barplot(x)
#Stacked bar chart
barplot(mat_small)
#Juxtaposed bar chart
barplot(mat_small, beside = TRUE)

#Box plot
boxplot(var1 ~ group, data = df)

#Histogram
hist(x)

#Pie chart
pie(x_small)

#Radar plot
stars(mat_small, scale = FALSE, locations = c(0, 0))

#Normal Q-Q plot
qqnorm(y)
#Generic Q-Q plot
qqplot(x, y)

#Contour plot
contour(mat_small)

#Plotting a curve
curve(sin, -2 * pi, 2 * pi)

#Converting a matrix to a colour image
image(mat)

#Adding to existing plots ####

#Drawing a line with arbitrary intercept and slope
abline(a = 0, b = 1)
#Drawing a horizontal line
abline(h = 0.5)
#Drawing a vertical line
abline(v = 0.5)

#Drawing a polygon
polygon(x_small)

#Adding arbitrary points
points(x_small)

#The front end (base R) ####
#Control coordinate ranges and aspect ratio
plot.window(xlim = c(0, 1), ylim = c(0, 1), asp = 1)

#Labelling the plot
title(main = "Title",
      sub = "Subtitle",
      xlab = "x-axis label",
      ylab = "y-axis label")

#Adding text
text(x_small, labels = paste("Put some text at position", 1:5))

#Adding a grid
grid()

#Adding an axis
axis(1)

#See all individual colours
colors()

#See all possible colour palettes
hcl.pals()

#Generating a vector of colours from a palette
palette(hcl.colors(10, "Reds"))

#Saving as a .png image
library(here)
png(filename = here("my_graphic.png"))
#(Add your plotting code here)
dev.off()

#The back end (ggplot2) ####
library(ggplot2)

#Unlike in base R, ggplot2 graphs are generated by composing functions
#Each function adds a different graphical element to the plot
#Composition is not done with the pipe (|>) as you might expect, but with +

#Defining your data (this does nothing by itself)
f <- ggplot(df)
f2 <- ggplot(seq_df)

#Main plots ####

#Scatter plot
f + geom_point(aes(x = var1, y = var2))
#Scatter plot with random jitter
f + geom_jitter(aes(x = var1, y = var2))
#Scatter plot connected by lines
f + geom_point(aes(x = var1, y = var2)) + geom_path(aes(x = var1, y = var2))
#Scatter plot connected by lines (ordered)
f + geom_point(aes(x = var1, y = var2)) + geom_line(aes(x = var1, y = var2))
#Scatter plot connected by filled lines (polygon)
f + geom_point(aes(x = var1, y = var2)) + geom_polygon(aes(x = var1, y = var2))

#Bar chart (heights represent values of a grouped variable)
f + geom_col(aes(x = cgroup, y = var1))
#Bar chart (heights represent number of observations per group only)
f + geom_bar(aes(x = cgroup))
#Bar chart (stacked)
f + geom_bar(aes(x = cgroup, fill = factor(group)), position = "stack")
#Bar chart (stacked, normalised)
f + geom_bar(aes(x = cgroup, fill = factor(group)), position = "fill")
#Bar chart (juxtaposed)
f + geom_bar(aes(x = cgroup, fill = factor(group)), position = "dodge")

#Box plot
f + geom_boxplot(aes(group = group, y = var1))

#Violin plot
f + geom_violin(aes(x = factor(group), y = var1))

#Histogram
f + geom_histogram(aes(x = var1))

#Normal Q-Q plot
f + geom_qq(aes(sample = var2))

#Contour plot
f2 + geom_contour(aes(x = seq1, y = seq2, z = var1))
#Filled contour plot
f2 + geom_contour_filled(aes(x = seq1, y = seq2, z = var1))

#Adding elements to a plot (technically, all ggplot2 functions do this) ####

#Drawing a line with arbitrary intercept and slope
f + geom_abline(aes(intercept = 0, slope = 1))
#Drawing a horizontal line
f + geom_hline(aes(yintercept = 0.5))
#Drawing a vertical line
f + geom_vline(aes(yintercept = 0.5))

#Drawing a polygon
f + annotate("polygon", x = x_small, y = y_small)

#Drawing a curve defined by a function
f + geom_function(fun = sin)

#The front end (ggplot2) ####

#Adding text
f + annotate("text",
             x = x_small,
             y = y_small,
             label = paste("Put some text at position", 1:5))

#Text (with background label)
f + annotate("label",
             x = x_small,
             y = y_small,
             label = paste("Put some text at position", 1:5))

#Adding a grid and controlling limits (done by default)
f + coord_cartesian(xlim = c(0, 1), ylim = c(0, 1))
#Adding polar coordinates instead
#(e.g. to transform a bar chart into a pie chart)
f + coord_polar()

#Labelling the plot
f + labs(x = "x-axis label",
         y = "y-axis label",
         title = "Title",
         subtitle = "Subtitle",
         caption = "caption")

#Changing theme
f + theme_gray() #default theme
f + theme_bw()
f + theme_dark()
f + theme_minimal()

#Saving the last plot you drew
library(here)
ggsave(filename = here("my_graphic.png"))